name: GitHub Readme Stats Action
description: Generate GitHub Readme Stats cards in GitHub Actions.
author: readme-tools
inputs:
  card:
    description: Card type to generate (stats, top-langs, pin, wakatime, gist).
    required: true
  options:
    description: Options for the card (query string or JSON).
    required: false
    default: ""
  path:
    description: Output path for SVG file (relative path; include filename with .svg).
    required: false
    default: ""
  token:
    description: GitHub token (PAT or GITHUB_TOKEN).
    required: false
    default: ""
outputs:
  path:
    description: Path where the SVG file was written.
runs:
  using: composite
  steps:
    - name: Install dependencies
      run: npm ci --omit=dev --ignore-scripts
      shell: bash
      working-directory: ${{ github.action_path }}
    - name: Generate card
      run: node ${{ github.action_path }}/index.js
      shell: bash
      env:
        PAT_1: ${{ inputs.token || github.token }}
branding:
  icon: bar-chart-2
  color: blue
